### ISSUE TITLE
Is it tested on zimbra 8.8.12

### ISSUE THREAD

**Issue by achilles03anil** [Zimbra-Community/reply-by-filter#1]
I Could not use the cli version just to make auto reply to all the users

**Comment by ghost** [comment]
This Zimlet does not add a CLI command. That is part of core Zimbra.

I am not sure of there is a command to create an auto reply for all users.

But that can probably be set-up using a Milter filter.

You will need to make a custom python script like so:
https://github.com/Zimbra-Community/mailing-lists/wiki/Set-mailing-list-email-headers-with-Milter
